name: CI/CD Pipeline

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.0.0'

      # - name: Build code
      #   run: |
      #     npm install
      #     npm run build

      # - name: Checking built artifact
      #   run: ls -la

      # - name: Building Docker Image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_REPOSITORY }}:first-real-app-frontend-latest .
      #     docker images

      # - name: Login and push to Docker Hub
      #   run: |
      #     echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      #     docker push ${{ secrets.DOCKER_REPOSITORY }}:first-real-app-frontend-latest

      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.OCTAVIAN_IP_ADDRESS }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts  # Set proper permissions
          echo "${{ secrets.OCTAVIAN_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la
          cd ~/.ssh
          ls -la
          # cat ~/.ssh/id_rsa
          # cat ~/.ssh/known_hosts

            - name: Pull and run docker container

      - name: Loggin into docker registry
        run: |
          echo "Logging in to Docker registry..."
          ssh ${{ secrets.OCTAVIAN_GITHUB_USER }}@${{ secrets.OCTAVIAN_IP_ADDRESS }} 'echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin'

